-- 코드를 입력하세요
SELECT ins.NAME AS NAME, ins.DATETIME AS DATETIME
FROM ANIMAL_INS ins
LEFT JOIN ANIMAL_OUTS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.ANIMAL_ID IS NULL
ORDER BY ins.DATETIME 
LIMIT 0, 3