WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME_TABLE WHERE HOUR < 23
)


-- 코드를 입력하세요
SELECT HOUR, COUNT(A.ANIMAL_ID)
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR