SELECT Y AS YEAR, (M - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA
JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) Y, MAX(SIZE_OF_COLONY) M
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) jt
ON YEAR(DIFFERENTIATION_DATE) = jt.Y
ORDER BY YEAR, YEAR_DEV